# Generated by Django 5.0.6 on 2024-06-10 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qqe', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='text',
            new_name='question_text',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='survey',
            new_name='survey_name',
        ),
        migrations.RenameField(
            model_name='survey',
            old_name='description',
            new_name='survey_description',
        ),
        migrations.RenameField(
            model_name='survey',
            old_name='title',
            new_name='survey_title',
        ),
    ]
