# Generated by Django 5.0.6 on 2024-06-28 14:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qqe', '0002_rename_text_question_question_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='survey_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
